import {
  Brain,
  BookOpen,
  Film,
  Music,
  Music2,
  Tv,
  Gamepad2,
  Trophy,
  Leaf,
  Monitor,
  Calculator,
  Landmark,
  Medal,
  Map,
  History,
  Palette,
  Star,
  PawPrint,
  Car,
  Cpu,
  Sparkles,
} from "lucide-react";

export const QUIZ_CATEGORIES = [
  { id: 9,  name: "General Knowledge", icon: Brain },
  { id: 10, name: "Books", icon: BookOpen },
  { id: 11, name: "Movies", icon: Film },
  { id: 12, name: "Music", icon: Music },
  { id: 13, name: "Musicals & Theatre", icon: Music2 },
  { id: 14, name: "Television", icon: Tv },
  { id: 15, name: "Video Games", icon: Gamepad2 },
  { id: 16, name: "Board Games", icon: Trophy },
  { id: 17, name: "Science & Nature", icon: Leaf },
  { id: 18, name: "Computers", icon: Monitor },
  { id: 19, name: "Mathematics", icon: Calculator },
  { id: 20, name: "Mythology", icon: Landmark },
  { id: 21, name: "Sports", icon: Medal },
  { id: 22, name: "Geography", icon: Map },
  { id: 23, name: "History", icon: History },
  { id: 24, name: "Politics", icon: Landmark },
  { id: 25, name: "Art", icon: Palette },
  { id: 26, name: "Celebrities", icon: Star },
  { id: 27, name: "Animals", icon: PawPrint },
  { id: 28, name: "Vehicles", icon: Car },
  { id: 29, name: "Comics", icon: BookOpen },
  { id: 30, name: "Gadgets", icon: Cpu },
  { id: 31, name: "Japanese Anime & Manga", icon: Sparkles },
  { id: 32, name: "Cartoons & Animations", icon: Sparkles },
];
